name: NETPipeline


env:
  VERSION: '3.1'
  SOLUTION_FILE_PATH: .
  #BUILD_CONFIGURATION: Release
  CONTINUE_ON_ERROR_SETUP: true
  CONTINUE_ON_ERROR: false

on:
  push:
    branches: [ master ]

jobs:
  
  Sonar-Analysis:
    name: Sonar Analysis
    runs-on: ubuntu-latest
    steps:   
    - name: Setup .NET Core SDK ${{ env.VERSION }}
      uses: actions/setup-dotnet@v1.7.2
      continue-on-error: ${{ env.CONTINUE_ON_ERROR_SETUP }}
      with:
        dotnet-version: ${{ env.VERSION }}

    
    - name: dotnet cover  
      uses: dodopizza/dotcover-action@v1
      with:
         #dotCoverCommand: help cover coverage.xml
        dotCoverCommand: dotnet --output=./CodeCoverageReport.xml --reportType=XML -- test "./unit-testing-using-nunit.csproj"

    - name: 'Publish code coverage results'
      uses: actions/upload-artifact@v2.2.3
      with:
          name: CoverageReport
          path: ./CodeCoverageReport.xml 


    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v2.3
      with:
        buildCommand: dotnet build .
        testCommand: dotnet test .
        projectKey: .NetProject
        projectName: .NetProject
        beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.host.url="http://13.59.238.74:9000"
            /d:sonar.cs.dotcover.reportsPaths='"./CodeCoverageReport.xml"'
            /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

